---
# Facts role tasks

- name: Setup fact with gitlab merge request info
  set_fact:
    gitlab_merge_request_fact: >-
      {{ (gitlab_merge_request_result is changed)
         | ternary(gitlab_merge_request_accept_result.json
                   | default(gitlab_merge_request_result.json),
                   gitlab_merge_request_accept_result.json
                   | default(gitlab_merge_request_search.0)
                   | default({})) }}
  tags:
    - role::gitlab_merge_request
