---
# Role tasks

- include_role:
    name: amtega.check_platform
  vars:
    check_platform_distributions:
      centos: 7
      fedora: 29
      rhel: 7

- include_role:
    name: amtega.gitlab_cli

- block:
    - name: Load user info from gitlab server
      command: >-
        gitlab
        {{ gitlab_merge_request_config_file_option }}
        {{ gitlab_merge_request_section_option }}
        -o yaml current-user get
      changed_when: false
      register: gitlab_merge_request_user_result

    - name: Load projects info from gitlab server
      command: >-
        gitlab
        {{ gitlab_merge_request_config_file_option }}
        {{ gitlab_merge_request_section_option }}
        -o yaml
        project get --id {{ gitlab_merge_request_item }}
      register: gitlab_merge_request_projects_info_result
      changed_when: false
      loop:
        - "{{ gitlab_merge_request_source_project }}"
        - "{{ gitlab_merge_request_target_project }}"
      loop_control:
        loop_var: gitlab_merge_request_item
        label: "{{ gitlab_merge_request_item | regex_replace('%2F', '/') }}"

    - name: Load project open merge requests info from gitlab server
      command: >-
        gitlab
        {{ gitlab_merge_request_config_file_option }}
        {{ gitlab_merge_request_section_option }}
        -o yaml
        project-merge-request list
        --project-id {{ gitlab_merge_request_target_project }}
        --state opened
      register: gitlab_merge_requests_opened_info_result
      changed_when: no

    - name: Setup gitlab merge request
      command: "{{ gitlab_merge_request_command }}"
      register: gitlab_merge_request_result
      failed_when: >-
        gitlab_merge_request_result.rc != 0
        and not gitlab_merge_request_result.stderr
            is search("Another open merge request already exists")
        and not gitlab_merge_request_result.stderr
            is search("Impossible to destroy object .*Not found")
      changed_when: gitlab_merge_request_command != "/bin/true"

    - name: Setup fact with gitlab merge request info
      set_fact:
        gitlab_merge_request_fact: >-
          {{ (not gitlab_merge_request_exists)
             | ternary(gitlab_merge_request_result.stdout
                       | default("")
                       | from_yaml,
                       {}) }}
  vars:
    gitlab_merge_request_user: >-
      {{ gitlab_merge_request_user_result.stdout | from_yaml }}

    gitlab_merge_request_source_project_id: >-
      {{ (gitlab_merge_request_projects_info_result.results.0.stdout
          | from_yaml).id }}

    gitlab_merge_request_target_project_id: >-
      {{ (gitlab_merge_request_projects_info_result.results.1.stdout
          | from_yaml).id }}

    gitlab_merge_request_search: >-
      {{ gitlab_merge_requests_opened_info_result.stdout
         | from_yaml
         | selectattr("source_project_id",
                      "equalto",
                      gitlab_merge_request_source_project_id | int)
         | selectattr("source_branch",
                      "equalto",
                      gitlab_merge_request_source_branch)
         | selectattr("target_branch",
                      "equalto",
                      gitlab_merge_request_target_branch)
         | list }}

    gitlab_merge_request_exists: >-
      {{ gitlab_merge_request_search | length > 0 }}

    gitlab_merge_request_create_command: >-
      gitlab
      {{ gitlab_merge_request_config_file_option }}
      {{ gitlab_merge_request_section_option }}
      -o yaml
      project-merge-request create
      --project-id {{ gitlab_merge_request_source_project }}
      --source-branch {{ gitlab_merge_request_source_branch }}
      --target-project-id {{ gitlab_merge_request_target_project_id }}
      --target-branch {{ gitlab_merge_request_target_branch }}
      --remove-source-branch {{ (gitlab_merge_request_remove_source_branch)
                                 | ternary("yes", "no") }}
      --title "{{ gitlab_merge_request_title }}"

    gitlab_merge_request_delete_command: >-
      gitlab
      {{ gitlab_merge_request_config_file_option }}
      {{ gitlab_merge_request_section_option }}
      -o yaml
      project-merge-request delete
      --project-id {{ gitlab_merge_request_target_project }}
      --iid {{ gitlab_merge_request_search.0.iid | default(none) }}

    gitlab_merge_request_command: >-
      {{ (gitlab_merge_request_state == "absent")
         | ternary(
             (gitlab_merge_request_exists | bool)
             | ternary(gitlab_merge_request_delete_command, "/bin/true"),
             (not gitlab_merge_request_exists | bool)
             | ternary(gitlab_merge_request_create_command, "/bin/true")) }}
  tags:
    - role::gitlab_merge_request
