---
# Role tasks

- block:
    - include_tasks: present.yml
      when: gitlab_merge_request_state in ["present", "merged"]

    - include_tasks: merged.yml
      when: gitlab_merge_request_state == "merged"

    - include_tasks: closed.yml
      when:
        - gitlab_merge_request_state == "merged"
        - gitlab_merge_request_exists
  tags:
    - role::gitlab_merge_request
