---
# Load open merge requests info role tasks

- name: Load project open merge requests info
  uri:
    url: >-
      {{ gitlab_merge_request_api_url
         + "/projects/"
         + gitlab_merge_request_target_project_id
         + "/merge_requests?state=opened" }}
    method: GET
    headers:
      "Private-Token": "{{ gitlab_projects_fact_token }}"
    return_content: yes
    validate_certs: "{{ gitlab_merge_request_validate_certs }}"
  register: gitlab_merge_requests_opened_info_result
  no_log: "{{ gitlab_merge_request_no_log | bool }}"
  tags:
    - role::gitlab_merge_request
